# Custom Language File for Launcher Customizer

[ejs.app]
title = "CoffeeOpia Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/MrFire24/CoffeeOpiaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/E67j4T9z"

[ejs.settings]
sourceGithubLink = "https://github.com/MrFire24/CoffeeOpiaLauncher"
supportLink = "https://github.com/MrFire24/CoffeeOpiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Добро Пожаловать CoffeeOpia"
welcomeDescription = "Кофеопия это майнкрафт сервер ценитель кофе ☕<br>
Здесь вы найдёте новых друзей и просто товарищей по кофе 🍪<br>
Каждый может стать частью нашего сервера и сделать из него нечто большое чем просто сервер по Майнкрафту ✨"
welcomeDescCTA = "Вы всего в паре кликов от Кофеопии."
