# Custom Language File for Launcher Customizer

[ejs.app]
title = "LastShot"

[ejs.landing]
mediaGitHubURL = "https://github.com/MrFire24/CoffeeOpiaLauncher"
mediaXURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/E67j4T9z"

[ejs.settings]
sourceGithubLink = "https://github.com/MrFire24/CoffeeOpiaLauncher"
supportLink = "https://github.com/MrFire24/CoffeeOpiaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Добро пожаловать в LastShot"
welcomeDescription = "LastShot — лаунчер для модифицированного Minecraft 🍹<br>
Все моды, конфиги и обновления ставятся и обновляются автоматически ✨<br>
Тебе остаётся только войти и играть 🎮"
welcomeDescCTA = "Ты всего в паре кликов от игры."
